version: '3'

services:
  redis:
    image: redis
  mongo:
    image: mongo
  app:
    build: .
    ports:
      - '80:3000'
    depends_on:
      - redis
    environment:
      redis_server_addr: redis
  